// flow-typed signature: 03cb2b86a28932a1e4d60410bddbea06
// flow-typed version: <<STUB>>/pixi.js_v5.0.4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pixi.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pixi.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pixi.js/dist/pixi' {
  declare module.exports: any;
}

declare module 'pixi.js/dist/pixi.min' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/pixi.es' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/pixi' {
  declare module.exports: any;
}

declare module 'pixi.js/scripts/support-pixi' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pixi.js/dist/pixi.js' {
  declare module.exports: $Exports<'pixi.js/dist/pixi'>;
}
declare module 'pixi.js/dist/pixi.min.js' {
  declare module.exports: $Exports<'pixi.js/dist/pixi.min'>;
}
declare module 'pixi.js/lib/pixi.es.js' {
  declare module.exports: $Exports<'pixi.js/lib/pixi.es'>;
}
declare module 'pixi.js/lib/pixi.js' {
  declare module.exports: $Exports<'pixi.js/lib/pixi'>;
}
declare module 'pixi.js/scripts/support-pixi.js' {
  declare module.exports: $Exports<'pixi.js/scripts/support-pixi'>;
}
