// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/lib/es6/src/jest.js";
import * as GameStateBuilder$BsKf1GameUtils from "../src/GameStateBuilder.js";

Jest.describe("Expect", (function (param) {
        return Jest.test("toBe", (function (param) {
                      return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](3));
                    }));
      }));

Jest.describe("Get Initial Game State Should Return The Right Object", (function (param) {
        var dict = { };
        dict["P1"] = {
          pos: /* array */[
            100,
            100
          ],
          charK: "assasin"
        };
        dict["P2"] = {
          pos: /* array */[
            200,
            200
          ],
          charK: "knight"
        };
        return Jest.test("correct return", (function (param) {
                      return Jest.ExpectJs[/* toEqual */12](dict, Jest.ExpectJs[/* expect */0](GameStateBuilder$BsKf1GameUtils.getInitialGameState(/* () */0)));
                    }));
      }));

export {
  
}
/*  Not a pure module */
