// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";

var renderOnlyKeys = /* array */["charK"];

function filterWasmConfig(keys) {
  var wasmConfig = { };
  List.map((function (k) {
          wasmConfig[k] = "1";
          return /* () */0;
        }), keys);
  return wasmConfig;
}

function getInitialGameState(param) {
  var dict = { };
  dict["P1"] = {
    pos: /* array */[
      100,
      100
    ],
    charK: "assasin"
  };
  dict["P2"] = {
    pos: /* array */[
      200,
      200
    ],
    charK: "knight"
  };
  return dict;
}

export {
  renderOnlyKeys ,
  filterWasmConfig ,
  getInitialGameState ,
  
}
/* No side effect */
