// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function filterWasmConfig(keys) {
  var wasmConfig = { };
  List.map((function (k) {
          wasmConfig[k] = "1";
          return /* () */0;
        }), keys);
  return wasmConfig;
}

var charEntities_000 = /* tuple */[
  "P1",
  /* array */[
    100,
    100
  ],
  "assasin"
];

var charEntities_001 = /* :: */[
  /* tuple */[
    "P2",
    /* array */[
      200,
      200
    ],
    "knight"
  ],
  /* [] */0
];

var charEntities = /* :: */[
  charEntities_000,
  charEntities_001
];

function getInitialGameState(param) {
  var dict = { };
  dict["P1"] = {
    pos: /* array */[
      100,
      100
    ],
    charK: "assasin"
  };
  dict["P2"] = {
    pos: /* array */[
      200,
      200
    ],
    charK: "knight"
  };
  return dict;
}

exports.filterWasmConfig = filterWasmConfig;
exports.charEntities = charEntities;
exports.getInitialGameState = getInitialGameState;
/* No side effect */
